### ISSUE TITLE
Create cheatsheet for tuterm commands

### ISSUE THREAD

**Issue by veracioux** [veracioux/tuterm#10]
Create a cheatsheet that can be used with the [`cheat`](https://github.com/cheat/cheat) program that:
- Shows the basic ways the `tuterm` command can be invoked
- Shows the most useful shell (API) functions that can be used within tuterm scripts (they are already documented in the [man page](https://github.com/veracioux/tuterm/blob/master/docs/tuterm.1)

**Comment by smsalamon** [comment]
Hi @veracioux! 👋 I'd like to work on this as part of Hacktoberfest.

**Comment by veracioux** [comment]
Thanks @smsalamon. Let me know if you need additional clarification or help.

**Comment by smsalamon** [comment]
Thanks! At the moment, could you just let me know where you want the cheatsheet file added?

**Comment by veracioux** [comment]
@smsalamon You can create the file as `docs/cheatsheet`.
